### ISSUE TITLE
Typing "R" in any Interface will scramble all the Inventory...

### ISSUE THREAD

**Issue by hexxone** [IMarvinTPA/InventoryTweaksTrees#3]
I am playing with this Mod on Dungeons, Dragons & Space Shuttles 7.0b...

However when I try to search for stuff in the Refined Storage System, and I type the letter "R"
it will always scramble / "sort" my WHOLE Inventory including Hotbar....
Even though the Cursor focus is clearly on the Search Windows

This is extremely aggrevating if you are just trying to get a missing Item and end up having to sort your inventory 20 times a Day....

I was looking for the Inventory-Tweaks Config files but these seem pretty useless to me since the Hotbar seems to be LOCKED by default even BUT it is still GETTING SORTED.

Only option is to turn of the Sorting-Key at this point... I hope this gets fixxed.

**Comment by hexxone** [comment]
Woops, wrong repo  - my bad

**Comment by IMarvinTPA** [comment]
Just go to the keyboard config in minecraft and either unbind it or use something like ~.
